config/routes.rb
Digren::Application.routes.draw do
  resources :bookquotes

  resources :readers

  root to: 'static_pages#home'
  
  match '/request_copy', to: 'readers#request_copy'
  match '/manifesto', to: 'bookquotes#manifesto'
  match '/submit_quote', to: 'bookquotes#submit_quote'

  match '/thebook', to: 'static_pages#thebook'
  match '/blog', to: 'static_pages#blog'
  match '/thankyou', to: 'static_pages#thankyou'
  match '/thanks4quote', to: 'static_pages#thanks4quote'
  match '/download', to: 'static_pages#download'
  match '/about', to: 'static_pages#about'
  match '/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/bookquote.rb
class Bookquote < ActiveRecord::Base
  attr_accessible :asin, :author, :published, :quote, :title, :tw_user
  validates :author, presence: true, length: { maximum: 80 }
  validates :quote, presence: true


end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/reader.rb
class Reader < ActiveRecord::Base
  attr_accessible :booksent, :email, :name

  before_save { |user| user.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookquotes_controller.rb
class BookquotesController < ApplicationController
  # GET /bookquotes
  # GET /bookquotes.json
  def index
    @bookquotes = Bookquote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookquotes }
    end
  end

  # GET /bookquotes/1
  # GET /bookquotes/1.json
  def show
    @bookquote = Bookquote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookquote }
    end
  end

  # GET /bookquotes/new
  # GET /bookquotes/new.json
  def new
    @bookquote = Bookquote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookquote }
    end
  end

  # GET /bookquotes/1/edit
  def edit
    @bookquote = Bookquote.find(params[:id])
  end

  # POST /bookquotes
  # POST /bookquotes.json
  def create
    @bookquote = Bookquote.new(params[:bookquote])

    respond_to do |format|
      if @bookquote.save
        format.html { redirect_to thanks4quote_path, notice: 'Bookquote was successfully created.' }
        format.json { render json: @bookquote, status: :created, location: @bookquote }
      else
        format.html { render action: "submit_quote" }
        format.json { render json: @bookquote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookquotes/1
  # PUT /bookquotes/1.json
  def update
    @bookquote = Bookquote.find(params[:id])

    respond_to do |format|
      if @bookquote.update_attributes(params[:bookquote])
        format.html { redirect_to @bookquote, notice: 'Bookquote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookquote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookquotes/1
  # DELETE /bookquotes/1.json
  def destroy
    @bookquote = Bookquote.find(params[:id])
    @bookquote.destroy

    respond_to do |format|
      format.html { redirect_to bookquotes_url }
      format.json { head :no_content }
    end
  end
  
  # GET /bookquotes/manifesto
  # GET /bookquotes/manifesto.json
  def manifesto
    @bookquotes = Bookquote.all

    respond_to do |format|
      format.html # manifesto.html.erb
      format.json { render json: @bookquotes }
    end
  end
  
  # GET /bookquotes/submit_quote
  # GET /bookquotes/submit_quote.json
  def submit_quote
    @bookquote = Bookquote.new

    respond_to do |format|
      format.html # submit_quote.html.erb
      format.json { render json: @bookquote }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
	    @message = Message.new
	end

	def create
		@message = Message.new(params[:message])
		    
		if @message.valid?
			NotificationsMailer.new_message(@message).deliver
			redirect_to(root_path, :notice => "Message was successfully sent.")
		else
			flash.now.alert = "Please fill all fields."
			render :new
		end
	end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  # GET /readers
  # GET /readers.json
  def index
    @readers = Reader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readers }
    end
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
    @reader = Reader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reader }
    end
  end

  # GET /readers/new
  # GET /readers/new.json
  def new
    @reader = Reader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reader }
    end
  end

  # GET /readers/1/edit
  def edit
    @reader = Reader.find(params[:id])
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(params[:reader])

    respond_to do |format|
      if @reader.save
        ReaderMailer.download_email(@reader).deliver
        format.html { redirect_to thankyou_path, notice: 'Thank you! We will send you a free pdf copy of Digital Renaissance.' }
        format.json { render json: @reader, status: :created, location: @reader }
      else
        format.html { render action: "request_copy" }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readers/1
  # PUT /readers/1.json
  def update
    @reader = Reader.find(params[:id])

    respond_to do |format|
      if @reader.update_attributes(params[:reader])
        format.html { redirect_to @reader, notice: 'Reader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader = Reader.find(params[:id])
    @reader.destroy

    respond_to do |format|
      format.html { redirect_to readers_url }
      format.json { head :no_content }
    end
  end
  
  # GET /readers/request_copy
  # GET /readers/request_copy.json
  def request_copy
    @reader = Reader.new

    respond_to do |format|
      format.html # request_copy.html.erb
      format.json { render json: @reader }
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def thebook
  end

  def blog
  end

  def thankyou
  end

  def download
  end

  def thanks4quote
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookquotes_helper.rb
module BookquotesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookquotes/_form.html.erb
<%= form_for(@bookquote) do |f| %>
  <% if @bookquote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookquote.errors.count, "error") %> prohibited this bookquote from being saved:</h2>

      <ul>
      <% @bookquote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asin %><br />
    <%= f.text_field :asin %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :tw_user %><br />
    <%= f.text_field :tw_user %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.text_field :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookquotes/books.html.erb
<% p=params[:al] %>
<% if p=="n"  %>
  <div class="alert alert-info">
    <p>If you don't agree we are entering a Digital Renaissance, see <strong>quotes and books from other authors</strong> with insights into how the world is evolving.</p>
  </div>
<% end %>

<%= render 'layouts/dtitle' %>
<h2>Insightful quotes from great authors</h2>

<% @bookquotes.each do |q| %>
	<% if q.published == "y" %>
		<div class="row">
		  <div class="offset2 span2">
		    <%= link_to image_tag("#{q.asin}.jpeg"), "http://www.amazon.com/dp/#{q.asin}?tag=ttbiz-20" %>
		    <br><br>
		  </div>
		  <div class="span6">
		    <blockquote><p><%= q.quote %></p><small><%= q.author %>, 
		    	<%= link_to q.title, "http://www.amazon.com/dp/#{q.asin}?tag=ttbiz-20" %>
		    </small></blockquote>
		    <% if !q.tw_user.blank? %>
		      <p>Posted by <%= q.tw_user %></p>
		    <% end %>
		  </div>
		</div>

	<% end %>	
<% end %>

<div class="row">
	<div class="offset2 span8">
		<hr>
		<%= render 'layouts/social' %>
	</div>
</div>

<div class="row">
	<div class="span6 offset3">

		<h3>Contribute to the ideas that are shaping the future.</h3>

		<p>What ideas guide your world?<br>
		What quote had the greatest impact on you lately?<br>
		Share insightful quotes from authors that inspire you.<br>		 
		</p>
		<p><%= link_to "Submit a quote &raquo;".html_safe, submit_quote_path, class: "btn btn-large btn-primary" %></p>	

	</div>
</div>

app/views/bookquotes/edit.html.erb
<h1>Editing bookquote</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookquote %> |
<%= link_to 'Back', bookquotes_path %>

app/views/bookquotes/index.html.erb
<h1>Listing bookquotes</h1>

<table>
  <tr>
    <th>Asin</th>
    <th>Title</th>
    <th>Author</th>
    <th>Quote</th>
    <th>Tw user</th>
    <th>Published</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookquotes.each do |bookquote| %>
  <tr>
    <td><%= bookquote.asin %></td>
    <td><%= bookquote.title %></td>
    <td><%= bookquote.author %></td>
    <td><%= bookquote.quote %></td>
    <td><%= bookquote.tw_user %></td>
    <td><%= bookquote.published %></td>
    <td><%= link_to 'Show', bookquote %></td>
    <td><%= link_to 'Edit', edit_bookquote_path(bookquote) %></td>
    <td><%= link_to 'Destroy', bookquote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bookquote', new_bookquote_path %>

app/views/bookquotes/manifesto.html.erb
<% p=params[:al] %>
<% if p=="n"  %>
  <div class="alert alert-info">
    <p>If you don't agree we are entering a Digital Renaissance, see <strong>quotes and books from other authors</strong> with insights into how the world is evolving.</p>
  </div>
<% end %>
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	<%= link_to image_tag("digital_renaissance_earth.jpg", :alt => "Digital Renaissance"), thebook_path %>
    	<div class="carousel-caption center">
                <h4>We're not just in a Digital Era. It's a Digital Renaissance</h4>
                <p>Insightful quotes from great authors</p>
      </div>
    </div>
    <div class="item">
    	<%= image_tag("long_tail_q1.jpg", :alt => "The Long Tail") %>
      <div class="carousel-caption">
         <p>1. We are entering a new era. It promises prosperity and richness of ideas as never before.
         </p>
      </div>
    </div>
    <div class="item">
    	<%= image_tag("abundance_q1.jpg", :alt => "Abundance") %>
      <div class="carousel-caption">
         <p>2. Never before mankind had the means to supply food, clothes and shelter for all. Never before were humans freed from physical labor as now.
         </p>
      </div>      
    </div>
    <div class="item">
    	<%= image_tag("wikinomics_q1.jpg", :alt => "Wikinomics") %>
      <div class="carousel-caption">
         <p>3. Never was as easy to create and spread ideas. The open source movement wins. The more you share your idea the more valuable it gets.
         </p>
      </div>
    </div>    
    <div class="item">
    	<%= image_tag("linchpin_q1.jpg", :alt => "Linchpin") %>
      <div class="carousel-caption">
         <p>4. Beyond the <em>knowledge worker</em>, it's time for the <em>artistic worker</em>.
         </p>
      </div>
    </div>
    <div class="item">
    	<%= image_tag("screw_business_q1.jpg", :alt => "Screw Business as Usual") %>
      <div class="carousel-caption">
         <p>5. Business and work must have a purpose. Business can not be just about profits anymore.
         </p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>



<% @bookquotes.each do |q| %>
	<% if q.published == "y" %>
		<div class="row">
		  <div class="offset2 span2">
		    <%= link_to image_tag("#{q.asin}.jpeg"), "http://www.amazon.com/dp/#{q.asin}?tag=ttbiz-20" %>
		    <br><br>
		  </div>
		  <div class="span6">
		    <blockquote><p><%= q.quote %></p><small><%= q.author %>, 
		    	<%= link_to q.title, "http://www.amazon.com/dp/#{q.asin}?tag=ttbiz-20" %>
		    </small></blockquote>
		    <% if !q.tw_user.blank? %>
		      <p>Posted by <%= q.tw_user %></p>
		    <% end %>
		  </div>
		</div>

	<% end %>	
<% end %>

<div class="row">
	<div class="offset2 span8">
		<hr>
		<%= render 'layouts/social' %>
	</div>
</div>

<!-- to let others submit quotes
<div class="row">
	<div class="span6 offset3">

		<h3>Contribute to the ideas that are shaping the future.</h3>

		<p>What ideas guide your world?<br>
		What quote had the greatest impact on you lately?<br>
		Share insightful quotes from authors that inspire you.<br>		 
		</p>
		<p><%= link_to "Submit a quote &raquo;".html_safe, submit_quote_path, class: "btn btn-large btn-primary" %></p>	

	</div>
</div>
-->
<div class="hero-unit">
	<div id="digren"><h1>Digital Renaissance</h1></div>
    <h2>A manifesto</h2>
	<ol>
		<li>We are entering a new era. It promises prosperity and richness of ideas as never before.</li>
		<li>Never before mankind had the means to supply food, clothes and shelter for all. Never before were humans freed from physical labor as now.</li>
		<li>Never was as easy to create and spread ideas. The open source movement wins. The more you share your idea the more valuable it gets.</li>
		<li>Beyond the <em>knowledge worker</em>, it's time for the <em>artistic worker</em>.</li>
		<li>Business and work must have a purpose. Business can not be just about profits anymore.</li>
		<li>We need more dreamers, entrepreneurs willing to bet all on their beliefs.</li>
	</ol>
  <hr>
  <%= render 'layouts/social' %>
</div>
<script>
    $('.carousel').carousel({
        interval: 1500
    })​;
</script>

app/views/bookquotes/new.html.erb
<h1>New bookquote</h1>

<%= render 'form' %>

<%= link_to 'Back', bookquotes_path %>

app/views/bookquotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asin:</b>
  <%= @bookquote.asin %>
</p>

<p>
  <b>Title:</b>
  <%= @bookquote.title %>
</p>

<p>
  <b>Author:</b>
  <%= @bookquote.author %>
</p>

<p>
  <b>Quote:</b>
  <%= @bookquote.quote %>
</p>

<p>
  <b>Tw user:</b>
  <%= @bookquote.tw_user %>
</p>

<p>
  <b>Published:</b>
  <%= @bookquote.published %>
</p>


<%= link_to 'Edit', edit_bookquote_path(@bookquote) %> |
<%= link_to 'Back', bookquotes_path %>

app/views/contact/new.html.erb
<div id="digren">
  <h1>Digital Renaissance</h1>
</div>
<h2>Contact form</h2>

<div class="row">
  <div class="span6 offset3">

    <%= form_for @message, :url => contact_path do |form| %>
      <fieldset class="fields">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>
        
        <div class="field">
          <%= form.label :email %>
          <%= form.text_field :email %>
        </div>
        <div class="field">
          <%= form.label :subject %>
          <%= form.text_field :subject, :class => "span6" %>
        </div>
        
        <div class="field">
          <%= form.label :body %>
          <%= form.text_area :body, :rows => 5, :class => "span6" %>
        </div>
      </fieldset>
      
      <fieldset class="actions">
        <%= form.submit "Send" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/_dtitle.html.erb
<div id="digren">
	<h1>Digital Renaissance</h1>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   
  </small>
  <nav>
    <div class="nav pull-left">
        <%= link_to image_tag("twitter.png"), "http://twitter.com/DigRenaissance" %>
        <%= link_to image_tag("fb.png"), "http://www.facebook.com/DigitalRenaissance" %>
    </div>

    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "The Book", thebook_path %></li>
          <li><%= link_to "Manifesto",  manifesto_path %></li>
          <li><%= link_to "Blog",   blog_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/readers/edit.html.erb
<h1>Editing reader</h1>

<%= render 'form' %>

<%= link_to 'Show', @reader %> |
<%= link_to 'Back', readers_path %>

app/views/readers/index.html.erb
<h1>Listing readers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Booksent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @readers.each do |reader| %>
  <tr>
    <td><%= reader.name %></td>
    <td><%= reader.email %></td>
    <td><%= reader.booksent %></td>
    <td><%= link_to 'Show', reader %></td>
    <td><%= link_to 'Edit', edit_reader_path(reader) %></td>
    <td><%= link_to 'Destroy', reader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reader', new_reader_path %>

app/views/readers/new.html.erb
<h1>New reader</h1>

<%= render 'form' %>

<%= link_to 'Back', readers_path %>

app/views/readers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reader.name %>
</p>

<p>
  <b>Email:</b>
  <%= @reader.email %>
</p>

<p>
  <b>Booksent:</b>
  <%= @reader.booksent %>
</p>


<%= link_to 'Edit', edit_reader_path(@reader) %> |
<%= link_to 'Back', readers_path %>

app/views/static_pages/home.html.erb
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	<%= link_to image_tag("digital_renaissance_earth.jpg", :alt => "Digital Renaissance"), thebook_path %>
    	<div class="carousel-caption">
                      <h4>Startups and Asia.</h4>
                      <p>Digital Renaissance is a story about a fresh-grad engineer that finds his dream job in a startup accelerator in Shanghai. Soon he will discover he is working for the dark side.</p>
      </div>
    </div>
    <div class="item">
          <%= image_tag("Shanghai-KL-Lankayan.jpg", :alt => "Collage") %>
            
    </div>
    <div class="item">
          <%= image_tag("Shanghai.jpg", :alt => "Shanghai") %>
         
    </div>
    <div class="item">
          <%= image_tag("KL.jpg", :alt => "Kuala Lumpur") %>
        <div class="carousel-caption">
             <p>Kuala Lumpur, Malaysia
             </p>
        </div>     
    </div>    
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<h2>Praise from readers:</h2>
<div id="praise">
<div class="row-fluid">
  <div class="span6">
  <blockquote>
    <p>Thriller, technology, love, business. The story traps you and just can't stop reading until the end. 
    </p> 
  </blockquote>
  </div>
  <div class="span6">
  <blockquote>
    <p>An attractive fantasy with the glamorous life in Asia Pacific around Shanghai and Kuala Lumpur.</p>
  </blockquote>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
  <blockquote>
    <p>A fresh new plot [...] managed to scratched in technology, culture, romance and a little dash of thriller.
    </p> 
  </blockquote>
  </div>
  <div class="span6">
  <blockquote>
    <p>This book was an enjoyable read, taking me back to some of the places I have lived and visited as well.</p>
  </blockquote>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
  <blockquote>
    <p>The story was fast paced, and linked to technology and business, and at the same time weaving some suspense and romance.
    </p> 
  </blockquote>
  </div>
  <div class="span6">
  <blockquote>
    <p>All in all a good read, entertaining and with some "food-for-thought."
    </p>
  </blockquote>
  </div>
</div>

</div>

<br>

<div class="row-fluid">
  <div class="offset1 span3">
    <%= image_tag("digital_renaissance_cover_30.jpg", :alt => "Digital Renaissance") %>
  </div>
  <div class="span8">
    <h4>A story about a dreamer that wants to change the world.</h4>
    <p>After joining a startup accelerator, Mike Marquez will come across an algorithm that can change music creation forever. But soon he will find he is working for the dark side. </p>
    <p>A story about pursuing your dreams, being true to yourself, and standing for your own beliefs.</p>
    
    <p><%= link_to "Buy on Amazon &raquo;".html_safe, "http://www.amazon.com/dp/B009YJOB6M?tag=ttbiz-20", class: "btn btn-success" %></p>
    <br>   
    <%= render 'layouts/social' %>
  </div>    
</div>

  

<!-- quotes  
<hr>
<div class="row-fluid">
  <div class="span6">
	<blockquote>
		<p>In a world of material goods [...] trade is a zero-sum game. I’ve got a hunk of gold and you have a watch. If we trade, then I have a watch and you have a hunk of gold. But if you have an idea and I have an idea, and we exchange them, then we both have two ideas. It’s nonzero.
		</p> 
		<small>Dean Kamen, Inventor</small>
	</blockquote>
  </div>
  <div class="span6">
	<blockquote>
		<p>Nothing happens unless first a dream.</p> 
		<small>Carl Sandburg, Poet</small>
	</blockquote>

  </div>
</div>

-->

<script>
    $('.carousel').carousel({
        interval: 1500
    })​;
</script>

app/views/static_pages/thebook.html.erb
<% p=params[:al] %>
<% if p=="y"  %>
  <div class="alert alert-info">
    <p>If you agree we are entering a new era, then this book might be for you. You can get a <strong>free copy</strong> for a limited time.</p>
  </div>
<% end %>

<div class="row-fluid">
  <div class="offset1 span3">
    <%= image_tag("digital_renaissance_cover_30.jpg", :alt => "Digital Renaissance") %>
    <br><br>
  </div>
  <div class="span8">
    <h4>A story about a dreamer that wants to change the world.</h4>
    <p>After joining a startup accelerator, Mike Marquez comes across an algorithm that can change music creation forever. But soon he will find he is working for the dark side. Even more, when a colleague dies in strange circumstances.</p>
    <p>A story about pursuing your dreams, being true to yourself, and standing for your own beliefs.</p>
    

    <p><%= link_to "Buy on Amazon &raquo;".html_safe, "http://www.amazon.com/dp/B009YJOB6M?tag=ttbiz-20", class: "btn btn-success" %></p>
    <br>
  </div>    
</div>
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="active item">
      <%= image_tag("Shanghai-KL-Lankayan.jpg", :alt => "Collage") %>
        
    </div>
    <div class="item">
      <%= image_tag("Shanghai.jpg", :alt => "Shanghai") %>
     
    </div>
    <div class="item">
      <%= image_tag("KL.jpg", :alt => "Kuala Lumpur") %>
      <div class="carousel-caption">
         <p>Kuala Lumpur, Malaysia
         </p>
      </div>     
    </div>
    <div class="item">
      <%= image_tag("digital_renaissance_earth.jpg", :alt => "Earth-rise") %>
      <div class="carousel-caption center">
         <p>Shanghai, KL and Lankayan &mdash; Some of the places where action happens. 
         </p>
      </div>      
    </div>
    
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<div class="hero-unit">
	<div id="digren">
		<h2>A modern Quixote that dreams to change the world</h2>
	</div>
	<p>Through the eyes of Mike, discover an emerging fast growing Asia, discover the startup world and the dynamics of startup accelerators. And above all discover how a new generation thinks about work, about the future and about their dreams and ambitions to make a difference.</p>

  <p>Set in Shanghai and Kuala Lumpur, the story uncovers the values that guide a young generation of dreamers. The guys that are shaping tomorrow with their actions today. They're driving us into a new era: The Digital Renaissance.</p>

  <p>Get into the new era through the eyes of a young engineer that dares to challenge the status quo and, in his own way, change the world.</p>

	<%= render 'layouts/quiero' %>
	<hr>
	<%= render 'layouts/social' %>
    
    <p><%= link_to "Get a free pdf sample &raquo;".html_safe, request_copy_path, class: "btn" %></p>
</div>


<script>
    $('.carousel').carousel({
        interval: 1500
    })​;
</script>